version: '3.10'

services:

  auth_postgres:
    restart: on-failure
    image: postgres:alpine
    volumes:
      - auth_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5433"
    networks:
      - billing_service_graduate-work

  nginx:
    restart: on-failure
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf.d:ro
    ports:
      - "81:81"
    depends_on:
      - auth_postgres
      - auth_service
      - redis
    networks:
      - billing_service_graduate-work

  auth_service:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - billing_service_graduate-work

  redis:
    image: redis:7.0.8
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - billing_service_graduate-work

networks:
  billing_service_graduate-work:
    external: true

volumes:
  auth_data:
